# Generated by Django 2.1.4 on 2019-10-12 05:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='ContactsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', ckeditor.fields.RichTextField(max_length=6000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст на стр Контакты',
                'verbose_name_plural': 'Текст на стр Контакты',
            },
        ),
    ]
