# Generated by Django 2.1.4 on 2019-10-12 05:08

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=6000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст для блока калькулятора',
                'verbose_name_plural': 'Текст для блока калькулятора',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'Фото для карусели на главной странице',
                'verbose_name_plural': 'Фото для карусели на главной странице',
            },
        ),
        migrations.CreateModel(
            name='CatolMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото схемы')),
                ('headerleft', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заголовок для левого блока')),
                ('headeright', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заголовок для правого блока')),
                ('subleft', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Левая колонка')),
                ('subright', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Правая колонка')),
                ('animaleft', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для левого блока')),
                ('animaparamleft', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для левого блока')),
                ('animaright', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для правого блока')),
                ('animaparamright', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для правого блока')),
            ],
            options={
                'verbose_name': 'Порядок приема катализаторов',
                'verbose_name_plural': 'Порядок приема катализаторов',
            },
        ),
        migrations.CreateModel(
            name='CatOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для оформления')),
                ('sub', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст')),
                ('sub_amp', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст|AMP-ваиант')),
                ('animaimage', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для изображения')),
                ('animaparamimage', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для изображения')),
                ('animasub', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для текста')),
                ('animaparamsub', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для текста')),
            ],
            options={
                'verbose_name': 'Порядок приема католизаторов',
                'verbose_name_plural': 'Порядок приема католизаторов',
            },
        ),
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('sub_amp', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Текст|AMP-вариант')),
                ('anima', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для блока')),
                ('animaparam', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для блока')),
            ],
            options={
                'verbose_name': 'Требование к католизатору',
                'verbose_name_plural': 'Требования к католизатору',
            },
        ),
        migrations.CreateModel(
            name='FooterContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', ckeditor.fields.RichTextField(blank=True, max_length=6000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст контактов в подвале',
                'verbose_name_plural': 'Текст контактов в подвале',
            },
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('href', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=10, verbose_name='Порядок следоваия')),
            ],
            options={
                'verbose_name': 'Ссылка в подвале',
                'verbose_name_plural': 'Ссылки в подвале',
            },
        ),
        migrations.CreateModel(
            name='HowToBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('alterimage', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст')),
                ('sub1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст в правой колонке')),
                ('sub2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст в левой колонке')),
                ('orient', models.CharField(choices=[('LF', 'Фото слева'), ('RH', 'Фото справа')], default='LF', max_length=2, verbose_name='Положение фото')),
                ('layout', models.BooleanField(default=False, verbose_name='Включить лэйаут "Фото+2колонки"')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок следования')),
                ('anima', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для блока')),
                ('animaparam', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для блока')),
                ('arrow', models.BooleanField(default=False, verbose_name='Нужна стрелка?')),
            ],
            options={
                'verbose_name': 'Блок "Как это работает"',
                'verbose_name_plural': 'Блоки "Как это работает"',
            },
        ),
        migrations.CreateModel(
            name='MainSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст в первом абзаце')),
                ('sub1_amp', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст в первом абзаце|AMP- вариант')),
                ('sub2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст во втором абзаце')),
            ],
            options={
                'verbose_name': 'Основной текст',
                'verbose_name_plural': 'Основной текст',
            },
        ),
        migrations.CreateModel(
            name='NewAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Имеет приоритет перед загруженным изображением', max_length=1000, null=True, verbose_name='Код иконки FontAwesome')),
                ('icon_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Высота изображения 80px | Формат PNG', null=True, upload_to='media/', verbose_name='Изображение для иконки')),
                ('icon_image_hover', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Высота изображения 150px | Формат PNG', null=True, upload_to='media/', verbose_name='Изображение иконки при наведении')),
                ('svg', models.FileField(null=True, upload_to='uploads/', verbose_name='SVG - иконка')),
                ('text', models.TextField(blank=True, help_text='Отображается под иконкой', max_length=3000, null=True, verbose_name='Текст преимущества')),
                ('group', models.IntegerField(blank=True, null=True, verbose_name='Порядок следования на сайте')),
            ],
            options={
                'verbose_name': 'Блок | Преимущества',
                'verbose_name_plural': 'Блок | Преимущества',
            },
        ),
        migrations.CreateModel(
            name='NewLaboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Показывается над иконкой', max_length=1000, null=True, verbose_name='Заголовок элемента')),
                ('icon', models.CharField(blank=True, help_text='Имеет приоритет перед загруженным изображением', max_length=1000, null=True, verbose_name='Код иконки FontAwesome')),
                ('icon_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Высота изображения 80px | Формат PNG', null=True, upload_to='media/', verbose_name='Изображение для иконки')),
                ('svg', models.FileField(null=True, upload_to='uploads/', verbose_name='SVG - иконка')),
                ('text', models.TextField(blank=True, help_text='Показывается под иконкой', max_length=3000, null=True, verbose_name='Текст элемента')),
                ('group', models.IntegerField(blank=True, null=True, verbose_name='Порядок следования на сайте')),
            ],
            options={
                'verbose_name': 'Блок | Мобильная лаборатория',
                'verbose_name_plural': 'Блок | Мобильная лаборатория',
            },
        ),
        migrations.CreateModel(
            name='NewPriceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Размер изображения не должен превышать 100кВ| Формат JPEG ', null=True, upload_to='media/', verbose_name='Изображение для блока')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Заголовок блока')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст блока')),
                ('price', models.CharField(blank=True, max_length=400, null=True, verbose_name='Цена от..')),
                ('group', models.IntegerField(blank=True, null=True, verbose_name='Порядок следования на сайте')),
            ],
            options={
                'verbose_name': 'Блок | Цены на католизаторы',
                'verbose_name_plural': 'Блок | Цены на католизаторы',
            },
        ),
        migrations.CreateModel(
            name='NewRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Имеет приоритет перед загруженным изображением', max_length=1000, null=True, verbose_name='Код иконки FontAwesome')),
                ('icon_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Высота изображения 100px | Формат PNG', null=True, upload_to='media/', verbose_name='Изображение для иконки')),
                ('svg', models.FileField(null=True, upload_to='uploads/', verbose_name='SVG - иконка')),
                ('text', models.TextField(blank=True, help_text='Показывается под иконкой', max_length=3000, null=True, verbose_name='Текст элемента')),
                ('group', models.IntegerField(blank=True, null=True, verbose_name='Порядок следования на сайте')),
            ],
            options={
                'verbose_name': 'Блок | Регионы',
                'verbose_name_plural': 'Блок | Регионы',
            },
        ),
        migrations.CreateModel(
            name='NewSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Фото - ширина 1920px | Формат JPEG', null=True, upload_to='media/', verbose_name='Фото')),
                ('slide_768', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Фото - ширина 768px | Формат JPEG', null=True, upload_to='media/', verbose_name='Фото')),
                ('slide_576', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Фото - ширина 576px | Формат JPEG', null=True, upload_to='media/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Блок | Основной слайдер фото',
                'verbose_name_plural': 'Блок | Основной слайдер фото',
            },
        ),
        migrations.CreateModel(
            name='NewTextAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=8000, null=True, verbose_name='Текст в первом абзаце')),
            ],
            options={
                'verbose_name': 'Блок | О нас',
                'verbose_name_plural': 'Блок | О нас',
            },
        ),
        migrations.CreateModel(
            name='NewWorkingMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Пример: 1.', max_length=10, null=True, verbose_name='Номер элемента')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст элемента')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Соотношение ширина/высота: 1 на 1.8 | Формат JPEG', null=True, upload_to='media/', verbose_name='Изображение для элемента')),
                ('group', models.IntegerField(blank=True, null=True, verbose_name='Порядок следования на сайте')),
            ],
            options={
                'verbose_name': 'Блок | Порядок работы',
                'verbose_name_plural': 'Блок | Порядок работы',
            },
        ),
        migrations.CreateModel(
            name='ParallaxImageI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото для верхнего параллакса',
                'verbose_name_plural': 'Фото для верхнего параллакса',
            },
        ),
        migrations.CreateModel(
            name='ParallaxImageII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото для нижнего параллакса',
                'verbose_name_plural': 'Фото для нижнего параллакса',
            },
        ),
        migrations.CreateModel(
            name='PartnersBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название партнера')),
                ('city', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Город расположения')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Логотип партнера')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на сайт партнера')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True, verbose_name='Текст блока')),
            ],
            options={
                'verbose_name': 'Блок | Партнер',
                'verbose_name_plural': 'Блок | Партнеры',
            },
        ),
        migrations.CreateModel(
            name='PriceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('price', models.CharField(blank=True, max_length=400, null=True, verbose_name='Цена от..')),
                ('anima', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для блока')),
                ('animaparam', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для блока')),
            ],
            options={
                'verbose_name': 'Блок цены католизаторы',
                'verbose_name_plural': 'Блоки цены католизаторы',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламный баннер',
            },
        ),
        migrations.CreateModel(
            name='SlideText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Заголовок')),
                ('sub', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Текст ')),
            ],
            options={
                'verbose_name': 'Текст на слайде',
                'verbose_name_plural': 'Текст на слайде',
            },
        ),
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото для оформления')),
                ('sub', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст')),
                ('sub_amp', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=6000, null=True, verbose_name='Текст|AMP-ваиант')),
                ('animaimage', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для изображения')),
                ('animaparamimage', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для изображения')),
                ('animasub', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Значение анимации для текста')),
                ('animaparamsub', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Параметры анимации для текста')),
            ],
            options={
                'verbose_name': 'Блок "Почему вы выберете нас"',
                'verbose_name_plural': 'Блок "Почему вы выберете нас',
            },
        ),
    ]
