# Generated by Django 2.1.4 on 2019-10-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersblock',
            name='image_full',
            field=models.BooleanField(default=False, verbose_name='Изображение на вю ширину блока'),
        ),
    ]
