# Generated by Django 2.1.4 on 2019-10-20 18:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partnersblock_image_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtextabout',
            name='text_amp',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=8000, null=True, verbose_name='Текст в первом абзаце|AMP - вариант'),
        ),
    ]
