# Generated by Django 2.1.4 on 2019-11-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newtextabout_text_amp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpriceblock',
            name='image_webp',
            field=models.FileField(blank=True, help_text='Размер изображения не должен превышать 100кВ| Формат WEBP ', null=True, upload_to='media/', verbose_name='WEBP | Изображение для блока'),
        ),
        migrations.AddField(
            model_name='newslider',
            name='slide_576_webp',
            field=models.FileField(blank=True, help_text='Фото - ширина 576px | Формат WEBP', null=True, upload_to='media/', verbose_name='WEBP | Фото'),
        ),
        migrations.AddField(
            model_name='newslider',
            name='slide_768_webp',
            field=models.FileField(blank=True, help_text='Фото - ширина 768px | Формат WEBP', null=True, upload_to='media/', verbose_name='WEBP | Фото'),
        ),
        migrations.AddField(
            model_name='newslider',
            name='slide_webp',
            field=models.FileField(blank=True, help_text='Фото - ширина 1920px | Формат WEBP', null=True, upload_to='media/', verbose_name='WEBP | Фото'),
        ),
        migrations.AddField(
            model_name='newworkingmethods',
            name='image_webp',
            field=models.FileField(blank=True, help_text='Соотношение ширина/высота: 1 на 1.8 | Формат WEBP', null=True, upload_to='media/', verbose_name='WEBP | Изображение для элемента'),
        ),
        migrations.AddField(
            model_name='partnersblock',
            name='image_webp',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='WEBP | Логотип партнера'),
        ),
    ]
