# Generated by Django 2.1.4 on 2019-11-05 19:28

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191104_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='newadvantages',
            name='icon_image_hover_webp',
            field=models.FileField(blank=True, help_text='Высота изображения 150px | Формат WEBP', null=True, upload_to='media/', verbose_name='WEBP | Изображение иконки при наведении'),
        ),
        migrations.AddField(
            model_name='newpriceblock',
            name='image_low',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Показывается до загрузки основной картинки| Формат JPEG ', null=True, upload_to='media/', verbose_name='Заглушка для ленивой загрузки картинки'),
        ),
        migrations.AddField(
            model_name='newworkingmethods',
            name='image_low',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Показывается до загрузки основной картинки | Формат JPEG', null=True, upload_to='media/', verbose_name='Заглушка для ленивого отображения картинки'),
        ),
    ]
