# Generated by Django 2.1.4 on 2019-11-07 18:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191105_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworkingmethods',
            name='image_low',
        ),
        migrations.AddField(
            model_name='partnersblock',
            name='image_low',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Заглушка логотипа при ленивой загрузке'),
        ),
    ]
