# Generated by Django 2.1.4 on 2020-03-25 11:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191114_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Текст для блока ПРЕИУЩЕСТВА',
                'verbose_name_plural': 'Текст для блока ПРЕИУЩЕСТВА',
            },
        ),
        migrations.CreateModel(
            name='MethodsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Текст для блока ПОРЯДОК РАБОТЫ',
                'verbose_name_plural': 'Текст для блока ПОРЯДОК РАБОТЫ',
            },
        ),
    ]
