# Generated by Django 2.1.4 on 2020-04-19 12:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seotitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Seo-title')),
                ('seodescript', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Seo-description')),
                ('seokeywords', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Seo-keywords')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('city_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название города')),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№1 | 1920px | Изображение города')),
                ('image_1_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №1 | 1920px | Изображение города')),
                ('image_1_768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№1 | 768px | Изображение города')),
                ('image_1_768_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №1 | 768px | Изображение города')),
                ('image_1_576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№1 | 576px | Изображение города')),
                ('image_1_576_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №1 | 576px | Изображение города')),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№2 | 1920px | Изображение города')),
                ('image_2_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №2 | 1920px | Изображение города')),
                ('image_2_768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№2 | 768px | Изображение города')),
                ('image_2_768_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №2 | 768px | Изображение города')),
                ('image_2_576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№2 | 576px | Изображение города')),
                ('image_2_576_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №2 | 576px | Изображение города')),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№3 | 1920px | Изображение города')),
                ('image_3_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №3 | 1920px | Изображение города')),
                ('image_3_768', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№3 | 768px | Изображение города')),
                ('image_3_768_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №3 | 768px | Изображение города')),
                ('image_3_576', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='№3 | 576px | Изображение города')),
                ('image_3_576_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №3 | 576px | Изображение города')),
            ],
            options={
                'verbose_name': 'СТРАНИЦА ГОРОДА',
                'verbose_name_plural': 'СТРАНИЦЫ ГОРОДОВ',
            },
        ),
    ]
