# Generated by Django 2.1.4 on 2020-05-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_1_576_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №1 | 576px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_1_768_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №1 | 768px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_1_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №1 | 1920px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_2_576_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №2 | 576px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_2_768_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №2 | 768px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_2_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №2 | 1920px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_3_576_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №3 | 576px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_3_768_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | №3 | 768px | Изображение города'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_3_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | №3 | 1920px | Изображение города'),
        ),
    ]
