# Generated by Django 2.1.4 on 2019-10-12 05:07

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_model', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Модель автомобиля')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Год выпуска')),
                ('weight', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вес катализатора')),
                ('price_kg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Цена за кг')),
                ('sum', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сумма')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'КАТАЛОГ | Автокатализатор',
                'verbose_name_plural': 'КАТАЛОГ | Автокатализаторы',
            },
        ),
        migrations.CreateModel(
            name='CatalizatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип катализатора')),
            ],
            options={
                'verbose_name': 'Тип катализатора',
                'verbose_name_plural': 'Типы катализаторов',
            },
        ),
        migrations.AddField(
            model_name='autocatalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CatalizatorType', verbose_name='Тип катализатора'),
        ),
    ]
