# Generated by Django 2.1.4 on 2020-05-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_autocatalog_image_jp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalcatfoto',
            name='img_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | Фото'),
        ),
    ]
