# Generated by Django 2.1.4 on 2019-10-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatinumPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rb', models.FloatField(blank=True, null=True, verbose_name='Стоимость, рубли')),
                ('price_dl', models.FloatField(blank=True, null=True, verbose_name='Стоимость, доллар')),
                ('price_eu', models.FloatField(blank=True, null=True, verbose_name='Стоимость, евро')),
            ],
            options={
                'verbose_name': 'Стоимость Платины',
                'verbose_name_plural': 'Стоимость Платины',
            },
        ),
        migrations.CreateModel(
            name='RhodyiPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rb', models.FloatField(blank=True, null=True, verbose_name='Стоимость, рубли')),
                ('price_dl', models.FloatField(blank=True, null=True, verbose_name='Стоимость, доллар')),
                ('price_eu', models.FloatField(blank=True, null=True, verbose_name='Стоимость, евро')),
            ],
            options={
                'verbose_name': 'Стоимость Родий',
                'verbose_name_plural': 'Стоимость Родий',
            },
        ),
        migrations.CreateModel(
            name='TantalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rb', models.FloatField(blank=True, null=True, verbose_name='Стоимость, рубли')),
                ('price_dl', models.FloatField(blank=True, null=True, verbose_name='Стоимость, доллар')),
                ('price_eu', models.FloatField(blank=True, null=True, verbose_name='Стоимость, евро')),
            ],
            options={
                'verbose_name': 'Стоимость Палладия',
                'verbose_name_plural': 'Стоимость Палладия',
            },
        ),
    ]
