# Generated by Django 2.1.4 on 2020-03-25 10:42

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение для баннера')),
                ('image_webp', models.CharField(blank=True, max_length=600, null=True, verbose_name='WEBP | Изображение для баннера')),
                ('text_part1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст| Часть1')),
                ('text_part2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст| Часть2')),
            ],
            options={
                'verbose_name': 'УСЛОВИЯ ПРИЕМА',
                'verbose_name_plural': 'УСЛОВИЯ ПРИЕМА',
            },
        ),
        migrations.CreateModel(
            name='ConditionsSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('keywords', models.TextField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
    ]
