# Generated by Django 2.1.4 on 2020-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_auto_20200421_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
