# Generated by Django 2.1.4 on 2020-05-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0003_conditions_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='image_jp2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='JPEG2000 | Изображение для баннера'),
        ),
    ]
