# Generated by Django 2.1.4 on 2019-10-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Необязательный параметр', max_length=200, null=True, verbose_name='Имя клиента')),
                ('mail', models.CharField(blank=True, help_text='Необязательный параметр', max_length=600, null=True, verbose_name='Почта клиента')),
                ('phone', models.CharField(max_length=600, verbose_name='Телефон клиента')),
                ('save_order', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Запрос на обратную связь',
                'verbose_name_plural': 'Запросы на обратную связь',
            },
        ),
        migrations.CreateModel(
            name='NewServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Необязательный параметр', max_length=200, null=True, verbose_name='Имя клиента')),
                ('mail', models.CharField(blank=True, help_text='Необязательный параметр', max_length=600, null=True, verbose_name='Почта клиента')),
                ('phone', models.CharField(max_length=600, verbose_name='Телефон клиента')),
            ],
            options={
                'verbose_name': 'Запрос на обратную связь',
                'verbose_name_plural': 'Запросы на обратную связь',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('contacts', models.CharField(max_length=600, verbose_name='Контактные данные')),
                ('description', models.TextField(max_length=4000, verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('contacts', models.CharField(max_length=600, verbose_name='Контактные данные')),
                ('description', models.TextField(max_length=4000, verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Сервисная Заявка',
                'verbose_name_plural': 'Сервисные Заявки',
            },
        ),
    ]
