# Generated by Django 2.1.4 on 2020-02-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='neworder',
            name='phone',
        ),
        migrations.AddField(
            model_name='neworder',
            name='model',
            field=models.CharField(blank=True, help_text='Необязательный параметр', max_length=1000, null=True, verbose_name='Марка|модель автомобиля'),
        ),
        migrations.AddField(
            model_name='neworder',
            name='phone_mail',
            field=models.CharField(blank=True, help_text='Обязательный параметр', max_length=600, null=True, verbose_name='Почта или телефон клиента'),
        ),
        migrations.AddField(
            model_name='neworder',
            name='type',
            field=models.CharField(blank=True, help_text='Необязательный параметр', max_length=1000, null=True, verbose_name='Тип катализатора (керамика|металл)'),
        ),
        migrations.AddField(
            model_name='neworder',
            name='val',
            field=models.CharField(blank=True, help_text='Необязательный параметр', max_length=1200, null=True, verbose_name='Объем|тип мотора (дизель|бензин)'),
        ),
        migrations.AddField(
            model_name='neworder',
            name='year',
            field=models.CharField(blank=True, help_text='Необязательный параметр', max_length=500, null=True, verbose_name='Год выпуска'),
        ),
    ]
